SELECT EM.*, DE.DEPARTMENT_NAME FROM EMPLOYEES EM, DEPARTMENTS DE WHERE EM.DEPARTMENT_ID=DE.DEPARTMENT_ID;

SELECT EMAIL, DE.DEPARTMENT_NAME, EM.DEPARTMENT_ID FROM EMPLOYEES EM, DEPARTMENTS DE 
WHERE EM.DEPARTMENT_ID=DE.DEPARTMENT_ID AND EMPLOYEE_ID='202';

SELECT EMAIL, DE.DEPARTMENT_NAME, EM.DEPARTMENT_ID, PHONE_NUMBER, SALARY FROM EMPLOYEES EM, DEPARTMENTS DE 
WHERE EM.DEPARTMENT_ID=DE.DEPARTMENT_ID AND (EM.DEPARTMENT_ID='50' OR SALARY='2600') ORDER BY SALARY ASC ;

SELECT EMPLOYEE_ID, EMAIL, DE.DEPARTMENT_NAME, EM.DEPARTMENT_ID FROM EMPLOYEES EM, DEPARTMENTS DE 
WHERE EM.DEPARTMENT_ID=DE.DEPARTMENT_ID AND EMPLOYEE_ID IN ('202','200','201');

SELECT DISTINCT EM.EMPLOYEE_ID, EMAIL, DE.DEPARTMENT_NAME, EM.DEPARTMENT_ID 
FROM EMPLOYEES EM, DEPARTMENTS DE, JOB_HISTORY JH WHERE EM.DEPARTMENT_ID=DE.DEPARTMENT_ID
AND EM.EMPLOYEE_ID=JH.EMPLOYEE_ID;